### ISSUE TITLE
Exception when clearing ver 3.7

### ISSUE THREAD

**Issue by johnfoxii** [SamDel/ChromeCast-Desktop-Audio-Streamer#108]
app idle or hours. I actually use it sometimes to adjust volume of speakers when another app is casting to them this way i can still use google voice and play music
I notices one speaker was different it had the name of another speaker with a "+1" on the end and it was yellow. So I went to reset. I clicked reset once (I think) and 2 seconds not sure i clicked it a first I clicked reset again and it exceptioned.
I also attached the output from a simple debugger captured after i clicked continue in the app the last 20-30 entries are from clicking reset let me knw if this has any value 

[Debug](https://docs.google.com/document/d/1KFAqQGPD3HLITAc3yJhQVzZOLS5NC2mUXfbw-D1CTDE/edit?usp=sharing)
[full exception](https://docs.google.com/document/d/1oMoI3QSFw5c5LehJvqQpjgOFK_xxvo48k3vHvidn3fQ/edit?usp=sharing)

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ChromeCast.Desktop.AudioStreamer.Application.Devices.SetFilterDevices(FilterDevicesEnum value)
   at ChromeCast.Desktop.AudioStreamer.Application.ApplicationLogic.ResetSettings()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ChromeCast.Desktop.AudioStreamer
    Assembly Version: 3.7.0.0
    Win32 Version: 3.7.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Desktop%20Audio%20Streamer/Desktop%20Audio%20Streamer/ChromeCast.Desktop.AudioStreamer.exe

**Comment by SamDel** [comment]
Thanks a lot, very helpfull! I could reproduce the issue by clicking ResetSettings multiple times in a row.
I added some fixes for it in [Setup 3.7.2.zip](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/files/6569518/Setup.3.7.2.zip).

**Comment by johnfoxii** [comment]
OK Thanks i seem to be able to duplicate it .  while scanning for new devices and  i click reset setting.  Here is the exception and i will install the new version and try. I'll just use this ticket if the new ver exceptions  and post here

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ChromeCast.Desktop.AudioStreamer.Application.Devices.SetFilterDevices(FilterDevicesEnum value)
   at ChromeCast.Desktop.AudioStreamer.Application.ApplicationLogic.ResetSettings()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------

**Comment by johnfoxii** [comment]
You fixed them Both
Thank you

**Comment by SamDel** [comment]
The fix is in release version [3.8](https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer/releases/tag/v3.8).
